<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'id' => 1,
                'name' => 'Sonali Bank PLC',
                'code' => 'SONALI',
                'description' => 'Largest state-owned commercial bank in Bangladesh.',
                'details' => 'Provides extensive retail, corporate, and government treasury services nationwide.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Janata Bank PLC',
                'code' => 'JANATA',
                'description' => 'Major state-owned commercial bank.',
                'details' => 'Focuses heavily on financing industrial, agricultural, and import-export sectors.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Agrani Bank PLC',
                'code' => 'AGRANI',
                'description' => 'Leading state-owned commercial bank.',
                'details' => 'Offers comprehensive corporate, SME, and remittance-handling banking ecosystems.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Rupali Bank PLC',
                'code' => 'RUPALI',
                'description' => 'State-owned commercial banking corporation.',
                'details' => 'Provides diverse savings, commercial lending, and rural banking operations.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'BASIC Bank PLC',
                'code' => 'BASIC',
                'description' => 'State-owned bank for small industries.',
                'details' => 'Specially mandated to finance Small and Medium Enterprises (SMEs) and heavy industry.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Bangladesh Development Bank PLC',
                'code' => 'BDBL',
                'description' => 'State-owned commercial development bank.',
                'details' => 'Formed via merger to extend long-term credit and equity support to industries.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Bangladesh Krishi Bank',
                'code' => 'BKB',
                'description' => 'Specialized state-owned agricultural bank.',
                'details' => 'Finances agricultural production, agro-based industries, and crop development schemes.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Rajshahi Krishi Unnayan Bank',
                'code' => 'RAKUB',
                'description' => 'Specialized regional agricultural bank.',
                'details' => 'Provides focused financing for the agricultural sectors in Rajshahi and Rangpur divisions.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Probashi Kollyan Bank',
                'code' => 'PKB',
                'description' => 'Specialized state-owned bank for migrant workers.',
                'details' => 'Provides welfare loans and sustainable financial options for non-resident Bangladeshi workers.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'BRAC Bank PLC',
                'code' => 'BRAC',
                'description' => 'Leading private commercial bank.',
                'details' => 'Renowned as the pioneer of SME banking and digital financial ecosystems.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'The City Bank PLC',
                'code' => 'CITY',
                'description' => 'Premium top-tier private commercial bank.',
                'details' => 'Market leader in credit cards, retail banking, corporate banking, and digital finance.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Dutch-Bangla Bank PLC',
                'code' => 'DBBL',
                'description' => 'High-convenience commercial bank.',
                'details' => 'Possesses the largest independent ATM and Fast-Track financial network in the country.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Eastern Bank PLC',
                'code' => 'EBL',
                'description' => 'Technology-driven private commercial bank.',
                'details' => 'Pioneers dual-currency cards, corporate trade finance, and innovative consumer banking.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Pubali Bank PLC',
                'code' => 'PUBALI',
                'description' => 'Largest private commercial bank by branch count.',
                'details' => 'Combines an expansive traditional retail presence with modern online banking facilities.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'United Commercial Bank PLC',
                'code' => 'UCB',
                'description' => 'Premier private sector commercial bank.',
                'details' => 'Maintains deep integration across corporate, retail, SME, and Islamic windows.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Mutual Trust Bank PLC',
                'code' => 'MTB',
                'description' => 'Award-winning private digital bank.',
                'details' => 'Specializes in corporate banking partnerships, retail loans, and digital onboarding.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Prime Bank PLC',
                'code' => 'PRIME',
                'description' => 'Top-tier corporate and consumer bank.',
                'details' => 'Widely respected for structured trade finance, corporate accounts, and digital credit.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Southeast Bank PLC',
                'code' => 'SOUTHEAST',
                'description' => 'Established private commercial bank.',
                'details' => 'Strong market footprint in export finance, remittance management, and institutional deposits.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Dhaka Bank PLC',
                'code' => 'DHAKA',
                'description' => 'Corporate-focused commercial banking entity.',
                'details' => 'Delivers advanced corporate cash management, retail loans, and trade services.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'IFIC Bank PLC',
                'code' => 'IFIC',
                'description' => 'Expansive universal private bank.',
                'details' => 'Operates the largest network of neighborhood digital banking booths in Bangladesh.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Bank Asia PLC',
                'code' => 'BANKASIA',
                'description' => 'Innovation-driven private bank.',
                'details' => 'Pioneered widespread financial inclusion via agent banking services across rural hubs.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Mercantile Bank PLC',
                'code' => 'MBL',
                'description' => 'Performance-driven commercial financial institution.',
                'details' => 'Offers comprehensive retail savings, SME micro-credits, and corporate portfolios.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Uttara Bank PLC',
                'code' => 'UTTARA',
                'description' => 'One of the oldest private commercial banks.',
                'details' => 'Delivers stable, traditional retail deposit schemes and commercial credit programs.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'One Bank PLC',
                'code' => 'ONEBANK',
                'description' => 'Progressive private retail and corporate bank.',
                'details' => 'Manages a robust portfolio of consumer wealth products and mobile financial wallets.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Jamuna Bank PLC',
                'code' => 'JAMUNA',
                'description' => 'Fast-growing private commercial bank.',
                'details' => 'Delivers client-centric real estate, corporate project lending, and retail savings.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'National Bank Limited',
                'code' => 'NBL',
                'description' => 'First generation private sector commercial bank.',
                'details' => 'Maintains an established history in domestic commercial loans and import-export trade.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'National Credit & Commerce Bank PLC',
                'code' => 'NCC',
                'description' => 'Stability-focused commercial financial institution.',
                'details' => 'Provides structured project finance, consumer cards, and agricultural micro-loans.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Standard Bank PLC',
                'code' => 'STANDARD',
                'description' => 'Full-fledged commercial financial enterprise.',
                'details' => 'Transitioned portfolio handling diverse consumer wealth and commercial business assets.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Midland Bank PLC',
                'code' => 'MIDLAND',
                'description' => 'Modern technology-focused private bank.',
                'details' => 'Known for high-yield digital fixed deposits and paperless client onboarding solutions.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Modhumoti Bank PLC',
                'code' => 'MODHUMOTI',
                'description' => 'New generation private commercial banking entity.',
                'details' => 'Serves industrial clients, green corporate investments, and high-net-worth consumers.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Meghna Bank PLC',
                'code' => 'MEGHNA',
                'description' => 'Customer-centric commercial financial institution.',
                'details' => 'Focuses on tailored SME loan disbursements and structured corporate lending.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'NRB Bank PLC',
                'code' => 'NRB',
                'description' => 'Expatriate-founded commercial banking firm.',
                'details' => 'Specialized in linking foreign inward remittances with domestic capital investments.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'NRBC Bank PLC',
                'code' => 'NRBC',
                'description' => 'Public-listed commercial banking institution.',
                'details' => 'Maintains massive growth via digital village booths and sub-branch business frameworks.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Community Bank Bangladesh PLC',
                'code' => 'COMMUNITY',
                'description' => 'Commercial bank operated by Bangladesh Police Kallyan Trust.',
                'details' => 'Serves both internal institutional staff and general retail consumers with modern banking.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Shimanto Bank PLC',
                'code' => 'SHIMANTO',
                'description' => 'Commercial bank operated by Border Guard Bangladesh Welfare Trust.',
                'details' => 'Delivers comprehensive consumer loans, SME project financing, and retail accounts.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'South Bangla Agriculture & Commerce Bank PLC',
                'code' => 'SBAC',
                'description' => 'Agro-industry leaning private commercial bank.',
                'details' => 'Bridges financing gaps between urban corporate sectors and rural agro-businesses.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Bengal Commercial Bank PLC',
                'code' => 'BENGAL',
                'description' => 'Modern enterprise-focused commercial bank.',
                'details' => 'Targets small trade operations, startups, and urban consumer financial solutions.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Citizens Bank PLC',
                'code' => 'CITIZENS',
                'description' => 'New-tier generation private commercial bank.',
                'details' => 'Provides flexible digital deposit certificates and corporate manufacturing credits.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Bangladesh Commerce Bank Limited',
                'code' => 'BCBL',
                'description' => 'Niche trading sector commercial bank.',
                'details' => 'Reconstructs financial facilities for small trading companies and retail merchants.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'AB Bank PLC',
                'code' => 'AB',
                'description' => 'First private commercial bank in Bangladesh.',
                'details' => 'Delivers long-term retail deposit structures, corporate financial credit, and cross-border trade operations.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'Padma Bank PLC',
                'code' => 'PADMA',
                'description' => 'Commercial retail service bank.',
                'details' => 'Maintains focused savings certificate products and consumer retail credit programs.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'The Premier Bank PLC',
                'code' => 'PREMIER',
                'description' => 'Client-oriented private commercial bank.',
                'details' => 'Highly active in consumer wealth structures, commercial property lending, and corporate financing.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'Trust Bank Limited',
                'code' => 'TRUST',
                'description' => 'Commercial bank sponsored by Army Welfare Trust.',
                'details' => 'Provides secure commercial services, electronic payroll processing, and structured retail facilities.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Islami Bank Bangladesh PLC',
                'code' => 'IBBL',
                'description' => 'Largest Shariah-compliant bank in Bangladesh.',
                'details' => 'Dominates nationwide inbound remittances, export financing, and Islamic retail banking.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Al-Arafah Islami Bank PLC',
                'code' => 'ALARAFAH',
                'description' => 'Premier Shariah-based commercial financial institution.',
                'details' => 'Provides standard investment banking via Murabaha and Mudaraba configurations.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'EXIM Bank PLC',
                'code' => 'EXIM',
                'description' => 'Shariah-oriented export-import bank.',
                'details' => 'Specializes in trade financing for garment exporters, manufacturers, and corporate entities.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'Social Islami Bank PLC',
                'code' => 'SIBL',
                'description' => 'Value-guided Islamic commercial banking platform.',
                'details' => 'Integrates social micro-finance schemes with standard corporate Islamic banking.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'First Security Islami Bank PLC',
                'code' => 'FSIBL',
                'description' => 'Widespread Islamic retail banking network.',
                'details' => 'Delivers consumer financing, corporate syndication, and profit-sharing term accounts.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'Shahjalal Islami Bank PLC',
                'code' => 'SHAHJALAL',
                'description' => 'Top-tier Islamic commercial institution.',
                'details' => 'Highly trusted for structured Islamic trade financing and corporate infrastructure investments.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'Union Bank PLC',
                'code' => 'UNION',
                'description' => 'Modern Shariah-compliant retail financial provider.',
                'details' => 'Offers tailored Islamic investment products for young professionals and small business owners.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'Global Islami Bank PLC',
                'code' => 'GLOBALISLAMI',
                'description' => 'Retail focused Islamic financial house.',
                'details' => 'Maintains focus on expanding Shariah-compliant sub-branches in semi-urban sectors.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'ICB Islamic Bank Limited',
                'code' => 'ICBISLAMI',
                'description' => 'Niche Shariah-compliant financial firm.',
                'details' => 'Manages targeted domestic retail finance structures and specialized savings certificates.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'Sammilito Islami Bank PLC',
                'code' => 'SAMMILITO',
                'description' => 'Unified Islamic commercial banking institution.',
                'details' => 'Formed under central resolution mandates to serve retail, SME, and trade sectors.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'Standard Chartered Bank',
                'code' => 'SCB',
                'description' => 'Oldest and largest foreign corporate bank.',
                'details' => 'Market leader in MNC banking, foreign exchange trading, and elite priority accounts.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'The Hongkong and Shanghai Banking Corporation Limited',
                'code' => 'HSBC',
                'description' => 'Major international cross-border financial house.',
                'details' => 'Specializes in high-volume trade syndication, MNC banking, and global custody services.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'Citibank N.A.',
                'code' => 'CITI',
                'description' => 'Global corporate investment financial institution.',
                'details' => 'Focuses purely on corporate banking, institutional cash solutions, and treasury assets.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => 'Commercial Bank of Ceylon PLC',
                'code' => 'CBC',
                'description' => 'Leading regional foreign commercial financial provider.',
                'details' => 'Highly efficient operations across corporate deposits, SME loans, and retail banking.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'State Bank of India',
                'code' => 'SBI',
                'description' => 'Cross-border regional commercial bank.',
                'details' => 'Facilitates massive bilateral trade operations, clearing systems, and commercial credits.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'Woori Bank',
                'code' => 'WOORI',
                'description' => 'Foreign corporate investment bank.',
                'details' => 'Primarily serves multinational corporate enterprises, Korean investments, and trade accounts.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'National Bank of Pakistan',
                'code' => 'NBP',
                'description' => 'Foreign state-linked financial branch.',
                'details' => 'Offers focused banking arrangements for international trade processing and clearing.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'Bank Al-Falah Limited',
                'code' => 'ALFALAH',
                'description' => 'International commercial banking house.',
                'details' => 'Delivers premier retail banking options and foreign consumer exchange ecosystems.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'Habib Bank Limited',
                'code' => 'HBL',
                'description' => 'Regional foreign commercial trade bank.',
                'details' => 'Processes clearing facilities and trade assets across south-asian business lines.',
                'logo' => '',
                'banner' => '',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('banks')->upsert(
            $banks,
            ['id'],
            ['name', 'code', 'description', 'details', 'logo', 'banner', 'is_active', 'created_at', 'updated_at']
        );
    }
}
